### ISSUE TITLE
NullPointerException on pkManager.getKit().getOverlays()

### ISSUE THREAD

**Issue by kovacss** [RadiusNetworks/proximitykit-reference-android#7]
Hi,

I'm really new to github so I don't know exactly how to submit a new issue.

I tried to test the proximitykit-reference-android application but I got a NullPointerException on the method didSync() from the AndroidProximityKitReferenceApplication class.

I tested the application on a Nexus 5 and bluetooth was activated.

Here is the stacktrace:

```
  Caused by: java.lang.NullPointerException
            at com.radiusnetworks.proximity.model.Kit.getOverlays(SourceFile:47)
            at com.radiusnetworks.androidproximitykitreference.AndroidProximityKitReferenceApplication.didSync(AndroidProximityKitReferenceApplication.java:215)
            at com.radiusnetworks.proximity.ProximityKitManager$1.didSync(SourceFile:365)
            at com.radiusnetworks.proximity.beacon.data.proximitykit.ProximityKitPersister$1.requestComplete(SourceFile:66)
            at com.radiusnetworks.proximity.api.KitAsynchApi.doInBackground(SourceFile:30)
            at com.radiusnetworks.proximity.api.KitAsynchApi.doInBackground(SourceFile:12)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
```

Edit:
I think that it's because I've no geofence configured in my kit

Thank you.

**Comment by cupakromer** [comment]
This is now fixed in the latest [Proximity Kit for Android 0.3.0](https://github.com/RadiusNetworks/proximitykit-android/releases/tag/0.3.0) release.
